# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('school', models.CharField(default=None, max_length=128, null=True)),
                ('date', models.DateField(default=None, null=True)),
                ('check', models.FloatField(default=None, max_length=128, null=True)),
                ('cash', models.FloatField(default=None, max_length=128, null=True)),
                ('credit_card', models.FloatField(default=None, max_length=128, null=True)),
                ('vending', models.FloatField(default=None, max_length=128, null=True)),
                ('ez_payment', models.FloatField(default=None, max_length=128, null=True)),
            ],
        ),
    ]
